# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J5BcIpGOpdNa6VnDB77wgvfwgjFWX7oY
"""

#ETE PORTO DIGITAL
#PROFESSOR CLOVES ROCHA 
#ESTUDANTE: DENYS LEONARDO 
nomes = ['denys','joao','pedro']
for n in nomes:
  print(n)